# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 575d9669e62e8041f79ff71c000bc65e4d4d2b9d24f88710bc66e3bc46d72d1446c7cea95fa56904a21e3b80ac3b5ff21f79827519bacc0949b676a52ca27ab8

test:
  secret_key_base: 7c9f315e0188f09f71bbb9e6ed652a9b2d950abb13045da4d404e4c485c183c355a63e954f353ad32248092ec24a21a20cbecfccddc2f90e5a9d6dcaffd676fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
